// pages/index.jsx
import About3 from "@/components/about/About3";
import Banner3 from "@/components/bannner/Banner3";
import Home3Contact from "@/components/contact/Home3Contact";
import Footer3 from "@/components/footer/Footer3";
import Header3 from "@/components/header/Header3";
import Partner3 from "@/components/partner/Partner3";
import Solution3 from "@/components/solutions/Solution3";
import SuccessStory3 from "@/components/successStorys/SuccessStory3";
import SuccessStory2 from "@/components/successStorys/SuccessStory2";
import useBodyClass from "@/hooks/useBodyClass";
import Head from "next/head";

export default function Home() {
  useBodyClass("home-dark2");

  return (
    <>
      <Head>
        <title>Mantra Connexions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/logo.png" />
      </Head>

      <Header3 />

      <section id="home" className="scroll-section"><Banner3 /></section>
      <section id="partners" className="scroll-section"><Partner3 /></section>
      <section id="solutions" className="scroll-section"><Solution3 /></section>
      <section id="portfolio-1" className="scroll-section"><SuccessStory3 /></section>
      <section id="portfolio-2" className="scroll-section"><SuccessStory2 /></section>
      <section id="contact-cta" className="scroll-section"><Home3Contact /></section>
      <section id="about" className="scroll-section"><About3 /></section>

      <Footer3 />

      {/* offset for sticky header */}
      <style jsx global>{`
        .scroll-section { scroll-margin-top: 90px; } /* adjust to your sticky header height */
        html { scroll-behavior: smooth; } /* native smooth scroll (kept even though we do manual offset) */
      `}</style>
    </>
  );
}
